---
- name: Install and Start Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx (Debian)
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Nginx (RedHat)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and Enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes
