---
- name: Rollback Nginx Deployment
  hosts: all
  become: yes
  tasks:
    - name: Stop and Remove Nginx
      block:
        - name: Stop Nginx
          service:
            name: nginx
            state: stopped
          ignore_errors: yes

        - name: Uninstall Nginx (Debian)
          apt:
            name: nginx
            state: absent
          when: ansible_os_family == "Debian"

        - name: Uninstall Nginx (RedHat)
          yum:
            name: nginx
            state: absent
          when: ansible_os_family == "RedHat"
